mod bounded;
mod dictionary;

use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
pub use dictionary::DICTIONARY_V1;
use flate2::{Compress, Compression, FlushCompress};

pub const MAX_DECODED_SIZE: usize = 64 * 1024;

const FRAME_TAG: u8 = 0x00;
const SCHEME_RAW: u8 = 0x01;
const SCHEME_DICT: u8 = 0x02;

#[derive(Debug, PartialEq, Eq)]
pub enum DecodeError {
    InvalidBase64,
    UnsupportedScheme,
    Corrupt,
    TooLarge,
}

/// Decodes a `/r/<payload>` path segment back into the HTML bytes it
/// encodes. Payloads that don't start with the `0x00` frame tag after
/// base64url-decoding are treated as legacy, uncompressed payloads (the
/// format every badge used before compression support existed) -- that
/// path must keep working forever, since already-deployed badge URLs rely
/// on it with no framing at all.
pub fn decode(payload: &str) -> Result<Vec<u8>, DecodeError> {
    let decoded = URL_SAFE_NO_PAD
        .decode(payload)
        .map_err(|_| DecodeError::InvalidBase64)?;

    let bytes = match decoded.first() {
        Some(&FRAME_TAG) => {
            let scheme = *decoded.get(1).ok_or(DecodeError::Corrupt)?;
            let body = &decoded[2..];
            let dictionary = match scheme {
                SCHEME_RAW => None,
                SCHEME_DICT => Some(DICTIONARY_V1),
                _ => return Err(DecodeError::UnsupportedScheme),
            };
            bounded::inflate_bounded(body, dictionary).map_err(|e| match e {
                bounded::InflateError::Corrupt => DecodeError::Corrupt,
                bounded::InflateError::TooLarge => DecodeError::TooLarge,
            })?
        }
        _ => decoded,
    };

    if bytes.len() > MAX_DECODED_SIZE {
        return Err(DecodeError::TooLarge);
    }

    Ok(bytes)
}

fn deflate(html: &[u8], dictionary: Option<&[u8]>) -> Vec<u8> {
    let mut compress = Compress::new(Compression::best(), false);
    if let Some(dictionary) = dictionary {
        compress
            .set_dictionary(dictionary)
            .expect("preset dictionary must be valid");
    }

    let mut out = Vec::with_capacity(html.len());
    loop {
        let before_in = compress.total_in() as usize;
        let before_out = compress.total_out() as usize;
        out.resize(before_out + 4096, 0);
        let status = compress
            .compress(&html[before_in..], &mut out[before_out..], FlushCompress::Finish)
            .expect("in-memory deflate cannot fail");
        out.truncate(compress.total_out() as usize);
        if status == flate2::Status::StreamEnd {
            break;
        }
    }
    out
}

/// Encodes HTML bytes into a `/r/<payload>` path segment. Tries every
/// compression scheme plus the legacy uncompressed form and keeps whichever
/// produces the strictly shortest base64url string, so compression can
/// never make a URL longer than the legacy encoding would have.
pub fn encode(html: &[u8]) -> String {
    let mut best = URL_SAFE_NO_PAD.encode(html);

    let candidates = [
        (SCHEME_RAW, None),
        (SCHEME_DICT, Some(DICTIONARY_V1)),
    ];
    for (scheme, dictionary) in candidates {
        let compressed = deflate(html, dictionary);
        let mut framed = Vec::with_capacity(compressed.len() + 2);
        framed.push(FRAME_TAG);
        framed.push(scheme);
        framed.extend_from_slice(&compressed);

        let candidate = URL_SAFE_NO_PAD.encode(&framed);
        if candidate.len() < best.len() {
            best = candidate;
        }
    }

    best
}

#[cfg(test)]
mod tests {
    use super::*;

    const BADGE_HTML: &str = include_str!("../../../examples/badge.html");
    const PLACARD_HTML: &str = include_str!("../../../examples/placard.html");

    #[test]
    fn round_trips_badge_example() {
        let encoded = encode(BADGE_HTML.as_bytes());
        let decoded = decode(&encoded).unwrap();
        assert_eq!(decoded, BADGE_HTML.as_bytes());
    }

    #[test]
    fn round_trips_placard_example() {
        let encoded = encode(PLACARD_HTML.as_bytes());
        let decoded = decode(&encoded).unwrap();
        assert_eq!(decoded, PLACARD_HTML.as_bytes());
    }

    #[test]
    fn decodes_a_payload_produced_by_the_sandbox_js_encoder() {
        // Generated by sandbox/src/payload.ts's encode() for the exact
        // contents of examples/badge.html, then confirmed to decode
        // identically here -- this is the one test that would catch the JS
        // and Rust encoders/decoders drifting out of sync with each other.
        let decoded = decode("AAKDlERcCgoKCngKDLA8XA22kgOuAgSCXP1cXINcXRSwFbw5icmJRSnFukWpeSmpRakp8HJLIcDH0dkxyCUYYRukpMFpOaxcCvb0c3ZVMDTT9wr10TcyMDJD0ojWJIC3CUBykGYB3HxEJMKFSCoQQBpqucCUHth9CKPRohiiEqwQEoBISrGlcrgkaqpDMgYSFDiMQVKOZAgkIUMNgVfxAA").unwrap();
        assert_eq!(decoded, BADGE_HTML.as_bytes());
    }

    #[test]
    fn dictionary_scheme_wins_on_corpus_like_content() {
        let html = PLACARD_HTML.as_bytes();
        let no_dict = {
            let compressed = deflate(html, None);
            let mut framed = vec![FRAME_TAG, SCHEME_RAW];
            framed.extend_from_slice(&compressed);
            URL_SAFE_NO_PAD.encode(&framed)
        };
        let with_dict = {
            let compressed = deflate(html, Some(DICTIONARY_V1));
            let mut framed = vec![FRAME_TAG, SCHEME_DICT];
            framed.extend_from_slice(&compressed);
            URL_SAFE_NO_PAD.encode(&framed)
        };

        assert!(with_dict.len() < no_dict.len());
        assert_eq!(encode(html), with_dict);
    }

    #[test]
    fn incompressible_content_falls_back_to_legacy() {
        // A pseudo-random byte sequence has no internal repetition and
        // shares nothing with the dictionary, so DEFLATE can only ever make
        // it larger once base64 + framing overhead is added back on top.
        let mut bytes = Vec::with_capacity(4096);
        let mut state: u32 = 0x2545F491;
        for _ in 0..4096 {
            state ^= state << 13;
            state ^= state >> 17;
            state ^= state << 5;
            bytes.push((state & 0xff) as u8);
        }

        let legacy = URL_SAFE_NO_PAD.encode(&bytes);
        assert_eq!(encode(&bytes), legacy);
    }

    #[test]
    fn legacy_payload_from_the_readme_hero_badge_decodes_forever() {
        // Pinned from README.md's hero <img> src -- this exact string must
        // keep decoding to the exact same HTML for as long as this project
        // exists, since it (and every other already-deployed badge URL) has
        // zero framing and relies entirely on the "no 0x00 prefix means
        // legacy" rule.
        const LEGACY_PAYLOAD: &str = "PGh0bWw-PGhlYWQ-PC9oZWFkPjxib2R5PgogICAgPGRpdiBjbGFzcz0iaGVybyI-CiAgICAgICAgPGgxIGNsYXNzPSJ0aXRsZSI-Q29tcGlsZSB0aGUgd2ViIGludG8gYSBiYWRnZTwvaDE-CiAgICAgICAgPHAgY2xhc3M9ImRlc2MiPgogICAgICAgICAgICBQbGFjYXJkIGVuYWJsZXMgeW91IHRvIGNyZWF0ZQogICAgICAgICAgICA8c3Ryb25nPmhpZ2gtcXVhbGl0eSByYXN0ZXJpemVkIGJhZGdlczwvc3Ryb25nPiB3aXRoIHRoZSBwb3dlciBvZgogICAgICAgICAgICBIVE1MIGFuZCBDU1MuCiAgICAgICAgPC9wPgogICAgICAgIDxkaXYgY2xhc3M9ImN0YS1yb3ciPgogICAgICAgICAgICA8YSBjbGFzcz0iY3RhIHByaW1hcnkiPkdvIHRvIHNhbmRib3gg4oaSPC9hPgogICAgICAgICAgICA8YSBjbGFzcz0iY3RhIHNlY29uZGFyeSI-QnJvd3NlIHNlcnZpY2UgY29ubmVjdG9ycyDihpI8L2E-CiAgICAgICAgPC9kaXY-CiAgICAgICAgPGRpdiBjbGFzcz0iY21kLXJvdyI-CiAgICAgICAgICAgIDxkaXYgY2xhc3M9ImNtZCI-R0VUIC9yLyZsdDtwYXlsb2FkJmd0Oy53ZWJwP3dpZHRoPSZsdDtuJmd0OzwvZGl2PgogICAgICAgIDwvZGl2PgogICAgPC9kaXY-Cgo8c3R5bGU-CiAgICBib2R5IHsKICAgICAgICBtYXJnaW46IDA7CiAgICAgICAgd2lkdGg6IDE2NjNweDsKICAgICAgICBiYWNrZ3JvdW5kOiAjMDAwMDAwOwogICAgfQogICAgLmhlcm8gewogICAgICAgIHBhZGRpbmc6IDIzMHB4IDI0cHggMjMwcHggMjRweDsKICAgICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7CiAgICB9CiAgICAudGl0bGUgewogICAgICAgIG1hcmdpbjogMDsKICAgICAgICBmb250LWZhbWlseTogIkdlaXN0IjsKICAgICAgICBmb250LXdlaWdodDogNzAwOwogICAgICAgIGZvbnQtc2l6ZTogOTJweDsKICAgICAgICBsaW5lLWhlaWdodDogMTsKICAgICAgICBjb2xvcjogI2ZmZmZmZjsKCQlsZXR0ZXItc3BhY2luZzogLTAuMDVlbTsKCQkKICAgIH0KICAgIC5kZXNjIHsKICAgICAgICBtYXJnaW46IDQwcHggMCAwIDA7CiAgICAgICAgZm9udC1mYW1pbHk6ICJHZWlzdCI7CiAgICAgICAgZm9udC13ZWlnaHQ6IDQwMDsKICAgICAgICBmb250LXNpemU6IDIwcHg7CiAgICAgICAgY29sb3I6ICNhMWExYTE7CiAgICB9CiAgICAuZGVzYyBzdHJvbmcgewogICAgICAgIGNvbG9yOiAjZmFmYWZhOwogICAgICAgIGZvbnQtd2VpZ2h0OiA3MDA7CiAgICB9CiAgICAuY3RhLXJvdyB7CiAgICAgICAgbWFyZ2luLXRvcDogMzRweDsKICAgICAgICBkaXNwbGF5OiBmbGV4OwogICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyOwogICAgICAgIGdhcDogMTJweDsKICAgIH0KICAgIC5jdGEgewogICAgICAgIGRpc3BsYXk6IGJsb2NrOwogICAgICAgIGZvbnQtZmFtaWx5OiAiR2Vpc3QiOwogICAgICAgIGZvbnQtc2l6ZTogMTVweDsKICAgICAgICBwYWRkaW5nOiAxMnB4IDIycHg7CiAgICAgICAgYm9yZGVyOiAxcHggc29saWQgIzI2MjYyNjsKICAgIH0KICAgIC5jdGEucHJpbWFyeSB7CiAgICAgICAgYmFja2dyb3VuZDogI2ZmZmZmZjsKICAgICAgICBib3JkZXI6IDFweCBzb2xpZCAjZmZmZmZmOwogICAgICAgIGNvbG9yOiAjMDAwMDAwOwogICAgICAgIGZvbnQtd2VpZ2h0OiA2MDA7CiAgICB9CiAgICAuY3RhLnNlY29uZGFyeSB7CiAgICAgICAgYmFja2dyb3VuZDogIzAwMDAwMDsKICAgICAgICBjb2xvcjogIzc1NzU3NTsKICAgIH0KICAgIC5jbWQtcm93IHsKICAgICAgICBtYXJnaW4tdG9wOiAyMnB4OwogICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7CiAgICB9CiAgICAuY21kIHsKICAgICAgICBmb250LWZhbWlseTogIkpldEJyYWluc01vbm8gTmVyZCBGb250IE1vbm8iOwogICAgICAgIGZvbnQtc2l6ZTogMTRweDsKICAgICAgICBjb2xvcjogIzc1NzU3NTsKICAgICAgICBiYWNrZ3JvdW5kOiAjMGEwYTBhOwogICAgICAgIGJvcmRlcjogMXB4IHNvbGlkICMxYTFhMWE7CiAgICAgICAgcGFkZGluZzogNnB4IDEycHg7CiAgICB9Cjwvc3R5bGU-CjwvYm9keT48L2h0bWw-";

        let decoded = decode(LEGACY_PAYLOAD).unwrap();
        let html = String::from_utf8(decoded).unwrap();
        assert!(html.starts_with("<html><head></head><body>"));
        assert!(html.contains("Compile the web into a badge"));
        assert!(html.ends_with("</style>\n</body></html>"));
    }

    #[test]
    fn decompression_bomb_is_rejected_without_unbounded_allocation() {
        // A few megabytes of a single repeated byte deflates to a tiny
        // blob (DEFLATE's run-length behavior on repeats routinely exceeds
        // 1000:1), so this stays fast and cheap to construct even though
        // the claimed decompressed size is far past MAX_DECODED_SIZE.
        let huge = vec![b'a'; 8 * 1024 * 1024];
        let compressed = deflate(&huge, None);
        assert!(compressed.len() < 8192);

        let mut framed = vec![FRAME_TAG, SCHEME_RAW];
        framed.extend_from_slice(&compressed);
        let payload = URL_SAFE_NO_PAD.encode(&framed);

        assert_eq!(decode(&payload), Err(DecodeError::TooLarge));
    }

    #[test]
    fn dictionary_bytes_are_pinned() {
        // Scheme 0x02 is a permanent commitment: once issued, a URL
        // compressed against this dictionary must decode correctly
        // forever. If this test ever fails, the dictionary bytes changed
        // underneath an already-shipped scheme id -- that's not allowed,
        // ship a new scheme id instead.
        let checksum = crc32fast::hash(DICTIONARY_V1);
        assert_eq!(checksum, 0x3ead6664);
    }

    #[test]
    fn dictionary_fits_within_the_deflate_window() {
        // A preset dictionary beyond 32KB is silently useless: raw DEFLATE's
        // sliding window is capped at 32768 bytes by the format itself
        // (RFC 1951), so anything past that offset from the real input can
        // never be referenced.
        assert!(DICTIONARY_V1.len() <= 32 * 1024);
    }

    #[test]
    fn rejects_invalid_base64() {
        assert_eq!(decode("not valid base64!!"), Err(DecodeError::InvalidBase64));
    }

    #[test]
    fn rejects_unknown_scheme() {
        let payload = URL_SAFE_NO_PAD.encode([FRAME_TAG, 0xFF]);
        assert_eq!(decode(&payload), Err(DecodeError::UnsupportedScheme));
    }

    #[test]
    fn rejects_corrupt_deflate_stream() {
        let payload = URL_SAFE_NO_PAD.encode([FRAME_TAG, SCHEME_RAW, 0xFF, 0xFF, 0xFF]);
        assert_eq!(decode(&payload), Err(DecodeError::Corrupt));
    }
}
